// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Default: typeof import('./src/layouts/default.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    VInput: typeof import('./src/components/base/VInput.vue')['default']
    VModal: typeof import('./src/components/base/VModal.vue')['default']
  }
}

export { }
