// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BallsButton: typeof import('D:/github/monostat/monostat-client/src/components/BallsButton.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Input: typeof import('D:/github/monostat/monostat-client/src/components/Input.vue')['default']
    Login: typeof import('D:/github/monostat/monostat-client/src/layouts/login.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    NavButton: typeof import('D:/github/monostat/monostat-client/src/components/NavButton.vue')['default']
    Side: typeof import('D:/github/monostat/monostat-client/src/components/layout/Side.vue')['default']
    VInput: typeof import('./src/components/base/VInput.vue')['default']
    VModal: typeof import('./src/components/base/VModal.vue')['default']
  }
}

export { }
